#!/usr/bin/env bash
# shellcheck disable=SC1000

# generate by create-script-file v4.0.0
# link (https://github.com/Template-generator/create-script-file/tree/v4.0.0)

# set -x #DEBUG - Display commands and their arguments as they are executed.
# set -v #VERBOSE - Display shell input lines as they are read.
# set -n #EVALUATE - Check syntax of the script but don't execute.

test -z "$JAVA_HOME" && echo "Java home must be set!" && exit 100
! command -v "sonar.sh" &>/dev/null && echo "Sonar server must be exist!" && exit 101

server="$(command -v "sonar.sh")"

$server "$1"
