#!/usr/bin/env bash
# shellcheck disable=SC1000

# generate by create-script-file v4.0.0
# link (https://github.com/Template-generator/create-script-file/tree/v4.0.0)

# set -x #DEBUG - Display commands and their arguments as they are executed.
# set -v #VERBOSE - Display shell input lines as they are read.
# set -n #EVALUATE - Check syntax of the script but don't execute.

export version=""
if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
	version="$(node -p "require('./package.json').version")-${TRAVIS_BUILD_NUMBER}"
	if [[ "$TRAVIS_BRANCH" == "master" ]]; then
		version="$(node -p "require('./package.json').version")"
	fi
else
	version="$(node -p "require('./package.json').version")-${TRAVIS_BUILD_NUMBER}-pr"
fi
