#!/usr/bin/env bash
# shellcheck disable=SC1000

# generate by create-script-file v4.0.0
# link (https://github.com/Template-generator/create-script-file/tree/v4.0.0)

# set -x #DEBUG - Display commands and their arguments as they are executed.
# set -v #VERBOSE - Display shell input lines as they are read.
# set -n #EVALUATE - Check syntax of the script but don't execute.

pr="$1"
b="$2"
n="$3"

version="$(node -p "require('./package.json').version")"

if [[ "$pr" == "false" ]]; then
	if [[ "$b" == "master" ]]; then
		echo "$version"
	else
		echo "$version-${n}"
	fi
else
	echo "$version-${n}-pr"
fi
