#!/usr/bin/env bash
# shellcheck disable=SC1000

# generate by create-script-file v4.0.0
# link (https://github.com/Template-generator/create-script-file/tree/v4.0.0)

# set -x #DEBUG - Display commands and their arguments as they are executed.
# set -v #VERBOSE - Display shell input lines as they are read.
# set -n #EVALUATE - Check syntax of the script but don't execute.

#/ -----------------------------------
#/ Description:  ...
#/ How to:       ...
#/               ...
#/ Option:       --help | -h | -? | help | h | ?
#/                   > show this message
#/               --version | -v | version | v
#/                   > show command version
#/ -----------------------------------
#/ Create by:    Kamontat Chantrachirathunrong <kamontat.c@hotmail.com>
#/ Since:        07/12/2018
#/ -----------------------------------
#/ Error code    1      -- error
#/ -----------------------------------
#/ Known bug:    ...
#/ -----------------------------------
#// Version:      0.0.1   -- description
#//               0.0.2b1 -- beta-format
#//               0.0.2a1 -- alpha-format

[[ "$1" == "-h" || "$1" == "--help" ]] && echo "pr <dest-branch> <pr-title...>"

cmd="hub"
branch="$1" # dest branch
shift
title="$*" # commit title

echo "Start creating... PR to '${branch}'"

! (command -v "$cmd" &>/dev/null) && echo "$cmd is require to create pr (https://github.com/github/hub)" && exit 99

release_note="$(yarn conventional-changelog --preset angular --output-unreleased)"

# templates
hub pull-request --base master --reviewer kamontat --push --message "$title
$release_note"
